version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sarrrrry/gh-mrepo
